# Generated by Django 2.2.4 on 2019-08-27 16:05

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipAddress', models.CharField(blank=True, max_length=50)),
                ('time', models.DateTimeField(auto_now=True)),
                ('state', jsonfield.fields.JSONField(default=dict)),
                ('action', models.CharField(max_length=50)),
                ('stateSubset', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
                ('ipAddress', models.CharField(blank=True, max_length=50)),
                ('timeDifference', models.DurationField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
