# Generated by Django 2.2.4 on 2019-08-27 21:39

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='actionData',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
