# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-23 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='data',
            new_name='state',
        ),
        migrations.AddField(
            model_name='action',
            name='action',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='ipAddress',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
